name: de_log
description: A starting point for Dart libraries or applications.
version: 1.0.0


environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  data_queue: ^1.0.1
  meta: ^1.7.0

dev_dependencies:
  lint: ^1.7.2
  test: ^1.16.0