name: de_log
description: The declarative logger allows you to create your own records and records handlers.
version: 1.0.0
homepage: https://github.com/KirsApps/de_log

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  data_queue: ^1.0.2
  meta: ^1.7.0

dev_dependencies:
  lint: ^1.7.2
  test: ^1.16.0